[package]
name = "game_glium"
version = "0.1.0"
edition = "2021"
authors = ["Sartek <sartek.richards@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"
